openapi: 3.0.3
info:
  title: WASAtext
  description: |
    This API allow multiple users to chat with each other,
    directly or by creating group chat.
  version: 0.0.1lella

components:
  parameters:
    usr_id:
      description: unique user id
      schema:
        type: string
        readOnly: true
      name: usr_id
      in: path
      required: true
      
    chat_id:
      description: unique chat id
      schema:
        type: integer
        minimum: 0
        readOnly: true
      name: chat_id
      in: path
      required: true
  
  schemas:
    user:
      type: object
      title: User
      description: |
        Contain information about an user of the app,
        like its name, user id, and profile photo.
      properties:
        user_id:
          type: string
          example: "ofnarc754"
          description: unique user id
          readOnly: true
        user_name:
          type: string
          example: "franco"
          description: Username
        user_photo:
          #bisogna decidere come gestire la foto
          type: string
          format: uri
          description: User profile photo (propic)
    
    chat:
      #capire come gestire la differenza tra
      #chat private(2utenti) e chat di gruppo
      #forse enum??
      type: object
      title: Chat
      description: |
        Contain information about a chat of two or more users,
        like the name of the chat (if it's a group), the propic(if it's a grout)
        the partecipants, its id.
      properties:
        chat_id:
          type: integer
          readOnly: true
          description: unique chat id
        chat_name:
          type: string
          description: |
            Chat name, if it's a private chat the name correspond
            to the other username
        chat_photo:
          #bisogna decidere come gestire la foto
          description: |
            Chat Photo, if it's a private chat is the propic of the other user,
            else contain the group photo
        chatType:
          type: string
          enum:
          - private
          - group
          description: |
            Used to distinguish group chat between private chat (only 2 people)
        partecipants:
          type: array
          items:
            $ref: "#/components/schemas/user"
          description: Array containing the users of the chat

paths:
  /session:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description: |-
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: 'ˆ.*?$'
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "201":
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  user_id:
                    type: string
                    example: "ofnarc754"
  
  /users:                         #Endpoint degli utenti dell'app
    get:
      tags: ["List all users"]
      operationId: showAllUsers
      summary: List all users
      responses:
        "200":
          description: Show an array that contain all the users of the WASAText
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  
  /users/{usr_id}:                #Endpoint del singolo utente
    parameters:
      - $ref: "#/components/parameters/usr_id"
    patch:
      #uso patch perché voglio modificare SOLO il nome dell'utente,
      #quindi un aggiornamento parziale
      tags: ["Change name"]
      operationId: setMyUserName
      summary: Change the username
      description: |
        Update only the username leaving invariated the id and photo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  description: New name
              required:
              - user_name
      responses:
        "200":
          description: Username updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        
        "400":
          description: unable to rename
        
        "404":
          description: user not found
      
  /users/{usr_id}/propic:         #Enpoint per la propic di un utente
    parameters:
      - $ref: "#/components/parameters/usr_id"
    patch:
      tags: ["Change propic"]
      operationId: setMyPhoto
      summary: Change the propic
      description: |
        Update only the username leaving invariated the id and photo
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_photo:
                  type: string
                  description: New name
              required:
              - user_photo
      responses:
        "200":
          description: photo updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        
        "400":
          description: unable to change propic
        
        "404":
          description: user or photo not found
  
  #forse meglio /users/{usr_id}/chats/.....
  
  #/chats:                        Endpoint delle chat
  #chats/{chat_id}:               Endpoint di una chat
  #/chats/{chat_id}/users:        Endpoint di una chat riguardo i suoi utenti
  
