openapi: 3.0.3
info:
  title: WASAtext
  description:  |
    This API allow multiple users to chat with each other,
    directly or by creating group chat.
  version: 0.0.2franco

components:
  parameters:
    usr_id:
      description:  |
        Unique user id
      
      schema:
        type: string
        pattern: "^[^\s]+$"
        example: "ofnarc754"

        minLength: 3
        maxLength: 32
        readOnly: true
      name: usr_id
      in: path
      required: true
      
    chat_id:
      description:  |
        Unique chat id
      
      schema:
        type: integer
        minimum: 0
        readOnly: true
      name: chat_id
      in: path
      required: true
    
    msg_id:
      description: |
        Unique message id
      
      schema:
        type: integer
        minimum: 0
        readOnly: true
      name: msg_id
      in: path
      required: true


  schemas:
    user:
      description:  |
        Contain information about an user of the app,
        like its name, user id, and profile photo.
      
      type: object
      title: User
      properties:
        usr_id:
          description:  |
            Unique user id
      
          type: string
          pattern: "^(?!\s).+$"
          example: "ofnarc754"
          
          minLength: 3
          maxLength: 32
          readOnly: true
        
        user_name:
          description:  |
            Username
          
          type: string
          pattern: "^(?!\s).+$"
          example: "franco"
          
          minLength: 3
          maxLength: 16
        
        user_photo:
          description:  |
            User profile photo (propic) encoded in base64
          
          type: string
          format: binary
          example: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
          
          maxLength: 1398101 #Equivalente di 1MB di dati binari in base64
    
    chat:
      type: object
      title: Chat
      description:  |
        Contain information about a chat of two or more users,
        like the name of the chat (if it's a group), the propic(if it's a grout)
        the partecipants, its id.
      properties:
        chat_id:
          description:  |
            Unique chat id
          
          type: integer
          
          minimum: 0
          readOnly: true
        
        chat_name:
          description:  |
            Chat name, if it's a private chat the name correspond
            to the other username
          
          type: string
          pattern: "^(?!\s).+$"
          example: "Chat Uni"
          
          minLength: 3
          maxLength: 16
          
        chat_photo:
          description:  |
            Chat Photo, if it's a private chat is the propic of the other user,
            else contain the group photo
          
          type: string
          format: binary
          example: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
          
          maxLength: 1398101 #Equivalente di 1MB di dati binari
        
        chatType:
          description:  |
            Used to distinguish group chat between private chat (only 2 people)
            
          type: string
          enum:
          - private
          - group
        
        partecipants:
          description:  |
            Array containing the users of the chat
          
          type: array
          minItems: 2
          maxItems: 64
          items:
            $ref: "#/components/schemas/user"
    
    message:
      type: object
      title: message
      description:  |
        Contain the message content, and other parameter such as:<br>
        msg_id, sender_id, message_content_type(if a photo or a text message), message_content, comment and like/dislike
      
      properties:
        msg_id:
          description:  |
            Unique message id FOR that chat
          
          type: integer
          minimum: 0
          readOnly: true
        
        sender_id:
          description:  |
            Correspond to the usr_id of the user that sended the message
          
          type: string
          pattern: "^[^\s]+$"
          example: "ofnarc754"

          minLength: 3
          maxLength: 32
          readOnly: true

        message_content_type:
          description:  |
            Describe if the content of the message is a photo o a text
          
          type: string
          enum:
          - photo
          - text
        
        message_content:
          description:  |
            Content of the message, can be a text or a photo
          
          oneOf:
            - description:  |
                Text  content
              
              type: string
              pattern: "^(?!\s).+$"
              minLength: 1
              maxLength: 1024
            - description:  |
                Photo content

              type: string
              format: binary
              example: "iVBORw0KGgoAAAANSUhEUgAAAAUA..."
              
              maxLength: 2787949

              

        


        

  
  securitySchemes:
    BearerAuth:
      description:  |
        Define the security scheme for the api, in this case we use Bearer Token,<br>
        and the token correspond to the usr_id
      type: http
      scheme: bearer
      bearerFormat: plain

paths:
  /session:
    post:
      tags: ["Login"]
      summary: Logs in the user
      description:  |
        If the user does not exist, it will be created,
        and an identifier is returned.
        If the user exists, the user identifier is returned.
      
      operationId: doLogin
      requestBody:
        description: User details
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: Maria
                  pattern: "^(?!\s).+$"
                  minLength: 3
                  maxLength: 16
        required: true
      responses:
        "201":
          description: User log-in action successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  usr_id:
                    type: string
                    example: "ofnarc754"
  
  #-----------------
  # USER ENDPOINTS
  #-----------------

  /users:                         #Endpoint degli utenti dell'app
    get:
      tags: ["User operation"]
      operationId: showAllUsers
      summary: List all users
      security:
      - BearerAuth: []  #indica che l'endpoint ha bisogno dell dell usr_id come token
      
      responses:
        "200":
          description: Show an array that contain all the users of the WASAText
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"
  
  
  /users/{usr_id}:                #Endpoint del singolo utente
    parameters:
      - $ref: "#/components/parameters/usr_id"
    patch:
      description:  |
        Update only the username leaving invariated the id and photo

      #uso patch perché voglio modificare SOLO il nome dell'utente,
      #quindi un aggiornamento parziale
      tags: ["User operation"]
      operationId: setMyUserName
      summary: Change the username
      security:
      - BearerAuth: []
      
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_name:
                  type: string
                  description: New name
              required:
              - user_name
      
      responses:
        "200":
          description: Username updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        
        "400":
          description: unable to rename
        
        "404":
          description: user not found
      
  
  /users/{usr_id}/propic:         #Enpoint per la propic di un utente
    parameters:
      - $ref: "#/components/parameters/usr_id"
    patch:
      description:  |
        Update only the username leaving invariated the id and photo
      tags: ["User operation"]
      operationId: setMyPhoto
      summary: Change the propic
      security:
      - BearerAuth: []

      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                user_photo:
                  type: string
                  description: New name
              required:
              - user_photo
      
      responses:
        "200":
          description: photo updated successfully
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/user"
        
        "400":
          description: unable to change propic
        
        "404":
          description: user or photo not found
  
  #-----------------
  # CHAT ENDPOINTS
  #-----------------

  /chats:                         #Endpoint delle chat
    get:
      description:  |
        Get all the chats of the user
      tags: ["Chat operation"]
      security:
      - BearerAuth: []
      
      responses:
        "200":
          description: Show an array that contain all the users of the WASAText
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: "#/components/schemas/user"


  #/chats/{chat_id}:                #Endpoint di una chat
  #/chats/{chat_id}/users:         #Endpoint di una chat riguardo i suoi utenti
  
  #-----------------
  # MESSAGE
  #-----------------