package database

import (
	"database/sql"
	"errors"
	"fmt"
)

var (
	// Per ora l'immagine di default è questa variabile, una stringa in formato base64
	defaultPropicBase64      = "/9j/4AAQSkZJRgABAQEAAAAAAAD/4QBCRXhpZgAATU0AKgAAAAgAAYdpAAQAAAABAAAAGgAAAAAAAkAAAAMAAAABAAAAAEABAAEAAAABAAAAAAAAAAAAAP/bAEMACwkJBwkJBwkJCQkLCQkJCQkJCwkLCwwLCwsMDRAMEQ4NDgwSGRIlGh0lHRkfHCkpFiU3NTYaKjI+LSkwGTshE//bAEMBBwgICwkLFQsLFSwdGR0sLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLCwsLP/AABEIAdoB2gMBIgACEQEDEQH/xAAfAAABBQEBAQEBAQAAAAAAAAAAAQIDBAUGBwgJCgv/xAC1EAACAQMDAgQDBQUEBAAAAX0BAgMABBEFEiExQQYTUWEHInEUMoGRoQgjQrHBFVLR8CQzYnKCCQoWFxgZGiUmJygpKjQ1Njc4OTpDREVGR0hJSlNUVVZXWFlaY2RlZmdoaWpzdHV2d3h5eoOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4eLj5OXm5+jp6vHy8/T19vf4+fr/xAAfAQADAQEBAQEBAQEBAAAAAAAAAQIDBAUGBwgJCgv/xAC1EQACAQIEBAMEBwUEBAABAncAAQIDEQQFITEGEkFRB2FxEyIygQgUQpGhscEJIzNS8BVictEKFiQ04SXxFxgZGiYnKCkqNTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqCg4SFhoeIiYqSk5SVlpeYmZqio6Slpqeoqaqys7S1tre4ubrCw8TFxsfIycrS09TV1tfY2dri4+Tl5ufo6ery8/T19vf4+fr/2gAMAwEAAhEDEQA/APXKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKZJNBEMyyxxj/po6r/M0XtuJtLVj6Kz5Na0ePObpGI7Rhn/AFUYqq/iTS1+6tw/0jAH/jzCsXXpreSOeWLoR3mvvNqiufPie2/htJz9WQf1NN/4SiL/AJ85P+/q/wCFR9ao/wAxl/aGG/m/M6KiueHii372kw+jof8ACpV8S6cfvxXK/wDAUb+TU1iqT+0NY/Dv7ZuUVmR67oz9bgof+mkbr+uMVdiu7KfHk3EL57JIpP5ZzWkakJfC0bwr05/DJP5k1FFFaGwUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFZd7rmn2m5FPnzDjZERtB/2n6fzrnLvWdSu8qZPJiP/ACzgyvH+033jXLVxVOnpuzz8RmFGjpe78jq7rU9OtMiadd4/5Zp87/8AfK/1rFuPEzHItbYAdnnOT/3wn+Nc7RXnVMbUl8Oh4tbNK09I+6i7Pq2q3Gd91Iqn+GLEa/8AjvP61SJLHLEk+rEk/maKK5JSlL4nc82dSc3ebuFFFFSQFFFFABRRRQAUnFLRQBZhv9Qt8eTdTKB/CWLL/wB8vkVqW/iW9TAuIY5h3ZP3b/1X9BWFRWsK1SHws6KeKrUvgkztbbXNLucKZTDIf4Zxt59m+7+taYIIBBBB5BHINeb1atdQv7MjyJmVe8bfNGf+Amu6nj3tNHq0c3a0qr5o76isGz8R20u1LxPIc8eYuWiP17it1XR1V0ZWRhlWUggj2Ir0adWFRXiz26OIp11em7i0UUVobhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFYWp69Hb74LPbJOMh5OscZ9B6n/PtWdSpGmuaRjWrwoR5ps0r3ULOwTdO/zEfJGvMj/Qf1rlb/AFm+vdyKTDAePLjJ3MP9tutZ0kksztJK7PIxyzOck02vHrYqdTRaI+YxWYVK/ux0j/W4lLRRXGeaFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAVas7+9sWzbyEKTlo25jb6r/hVWinGTi7oqM5QfNF2Z2mn61aX22Nv3Nwf+Wbnhz/sN3+laleb1u6Zr8kO2G9LSQ8BZusif73qP1+tepQxt/dqfefQYTNFL3K/3/5nV0U1HjkRZI2VkcBlZTkEHuCKdXpnu7hRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABQSqgsxAUAkknAAHOSTQSFBZiAoBJJOAAOck1yGsaw14zW9uxFqpwzDgzkdz/s+lYVq0aMbs5MVioYaHNLfoiTVtceffbWbFYOVklGQ0vsvov8/wCeFRRXhVKkqkuaR8lWrzry55sKKKKzMAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKANDTdUuNPfAy9uxzJET0/2kz0Ndnb3NvdRJNA4aNu/cHurD1FeeVc0/ULjT5vMj+aNiBNET8rj1Hv6Gu3DYp0/dlt+R6uBx7oPknrH8jvKKhtrmC7hSeBtyOPxU91YeoqavaTTV0fUxkpK62CiiimMKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKwte1P7Ohs4GxPKv71geY4z2HuazqVFTjzSMa9aNCDnIo65qxnZ7O2b9wpxM6n/WsP4Qf7o7+v88Kiivn6lSVSXNI+Nr1pV5ucwooorMwCiiigAooooAKKKKACiiigAooooAKKSjI9R+dAC0UmRS0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAXtM1GXT59wy0EhAnjHcf3l9x/n27eKWKaOOWJg0cihkYdCDXnVbOh6n9klFtM3+jTN8pJ4ikPf6HvXfhMRyPklsexl2N9lL2U37r/A6+iiivZPpwooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigCrqF7HY20k7YLfdiX+/Ieg/xrg5JJJpJJZGLSSMXdj3JrR1q/wDtt2yo2YLctHFjozfxP+Pb6e9ZleHiq3tJ2WyPkswxXt6nLH4V/VwooorjPNCiiigAooooAKKKKACiiigAoorY0nRnvds8+5LXPygcPNj+76D3/wD11dOnKpLlia0aM60uSC1M+1s7y8fZbxM+PvN0Rf8AeY8Vv23hqFQGu52du6Q/Ig/4Eef5VvRRQwRrFCipGowqoMAU+vXpYKEdZas+kw+V0qavU95/gUotK0qHGy0hz6uu8/m+asfZrQcCCHH/AFzT/CpaK7FCK2R6UaUI6RikVpNP02UYktLc/wDbNQfzUZrNuPDmnyAmBpIG7AHen/fLc/rW3RUSo057ozqYajU+KKOGvdJ1Cxy0iB4R/wAtYslR/vDqKoV6QQCCDyDwQa57VdBVg9xYqFcZZ4Bwr+pj9D7f5Pm18E4rmp/ceJisrcFz0dV2OYoo5GQQQQcEHggjsaK848MKKKKACiiigAooooAKKKKACiiigDrtB1E3MJtZmzPbqNpPWSLoD9R0NbVeeW1xLazw3ER+eJs47MvQqfrXf288VzDDPEcpKgZfbPY/Svbwdb2keV7o+qy3Fe2hyS3X5ElFFFdp6oUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFZeuXptLNlQ4muMxR46hcfM34D+dalcRrN39rvpSpzFBmCL0O0/M34n+VcuKq+zp6bs8/MMR7Gi7bvQzaWiivBPkAooooAKKKKACiiigAooooAKKKAGYqqjLMQqgdyTgCgDT0fTft85aQH7NCQZf9tuojB/n/APXrtQFUKqgBVACgDAAHAAAqrYWiWVrDbrjco3SEfxSNyxq1Xv4eiqUPN7n2OCwqw9Oz3e4UUUV0ncFFFFABRRRQAUUUUAc14g01VDahCuOR9qUdOeBJ/j+dc5Xo7okiOjqGR1KOp5DKwwQa87vIWsL65sZCcI263c/xwtyoJ9R0/CvIxlDlfPHqfN5phFCXtYbPf1GUUUV5x4gUUUUAFFFFABRRRQAUUUUAFdD4bvdry2Lnh8ywZ/vD7yj+f51z1PhlkglhmjOHidXX6g9PxrWjUdOakdGGrOhVU1/SPRaKjgmjuIYZ4z8kqK6/iM4qSvok76o+2TTV0FFFFMYUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBT1O6+yWNzMDh9uyP/AH3+Uf4/hXB10Xia4y1pag8ANPIPc/Iuf1rna8TG1Oapy9j5XNK3PW5VtEKKKK4jygooooAKKKKACiiigAooooAK09DgE+owEjKwK05+q8L+pFZldD4XQGS/k7hIUH4lmP8AKt8PHmqxR2YKHPiIJ9/y1Onooor6E+zCiiigAooooAKKKKACiiigArkfGdqNun3qjkM1tIfYjzE/kfzrrqxPFMYfRrk94pIJB+EgX+tY1481NnLi489GS/rQ4m3n8wbHPzjof7w/xqzWQCQQRwRyCK0IJxKNrf6wDn/aHqK8CUbao+PnC2qJ6KKKgyCiiigAooooAKKKKACiiigDqvDV1vgntWPzQNvTP/PN+34HP51vVw+jXH2fUbYk4SUmB/TD9P1xXcV7mDqc9O3Y+syyt7Sgk91oFFFFdh6YUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRTJpBFDPKekcbyH/AICpNDdtRN2V2cPq0/2jUbx85VZPKT/dj+X/ABqlQSWJY9WJY/U8mivmZS5pOXc+EqTc5Ob6hRRRUkBRRRQAUUUUAFFFFABRRRQAV0nhcj/iYr3zA34fOK5utrw3KEvpYif9dAcf7yHd/LNdOFdqsTuy+XLiINnXUUUV759iFFFFABRRRQAUUUUAFFFFABWP4mYLot/n+LyVH1MqVsVzXjCcJp9vBn5ri5U/8BiBY/risqztTZz4qXLRk/I4WlBKkMDgg5BFJRXiHypowzCVeeHH3h/UVNWSrMjBlOCOlaMUqyrkcMPvD0rKUbHNOFtUS0UUVBmFFFFABRRRQAUUUUAALKQy8MpDKfQg5Feh28ongt5h0liST/voZxXnldn4fl8zTYlPWF5IvwB3D+dehgJWm49z2soqWqSh3X5GrRRRXsH0oUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABWfrUnl6ZenPLIsY/4GwWtCsXxI+2wRf79zGPwAZv6VjXdqcn5HNi5ctCb8mcjRRRXzp8SFFFFABRRRQAUUUUAFFFFABRRRQAVNazta3NvcL1ikViPVejD8RmoaKabTuhxk4tNdD0dHSREkQgo6q6kd1IyDS1z3h7UAyfYJW+dMtbk/xJ1Kfh29vpXQ19FSqKpBSR9th66r01NBRRRWp0BRRRQAUUUUAFFFFABXnvii9F3qTRIcxWS+QMdDITuc/yH4V1uuaoml2bspH2mYGO2X/axy5HovX/APXXmxJJJJJYklieSSeSTXBi6mnIjx8yrKypL5iUUUV5x4oU5HaNgynkfkR6Gm0UCNSORZVDL9CO4NPrLjkaJgy/iOxHpWijrIoZTwfzB9DWMo2OecOUfRRRUmYUUUUAFFFFABXS+F5Pkv4vR4pB/wACBU/yrmq3PDL4vLlP79tn8Vcf4104V2qo78vly4iP9dDrKKKK98+wCiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAK5/xOf3FivrO5/JD/AI10Fc74o/1en/8AXSb/ANBFc2K/gyOHMP8Adpf11OZooorwD44KKKKACiiigAooooAKKKKACiiigAooooAVHeN0kRirowZGXgqw5BFdlpWrw3yLFKVS7UfMvQSY/iT+orjKASCCCQwIKspIZSOhBHOa6KFeVGV1sdmExcsNK62e6PSKK5Kx8TyW5SDU1Z4+iXUa5bHpKg7+4/KuntruzvEElrPFKnrGwJH1HUV7dOtCorxZ9XRxNOurwZNRRRWp0BRRTXkiiUvI6Ii8lnYKo+pPFADqp6jqVnplu09w3JyIo1xvlf8AuqP5msbUvFljbho7AC5m6eZyIEPrnqfw/OuMuru7vZmnupWklbjJ4Cj+6ijgCuOriYx0jqzzcRj401y09X+BJqF/dalcvc3B5PyxoPuxRjoi/wBaqUUV5jbbuzwJScnd7hRRRSEFFFFABUkUrRNkcg/eHqKjooE1c1VZXUMpyDTqzYZjE3qh+8P6itEEMAynIIyCKxkrHNKPKxaKKKkgKKKKACtbw8cakg/vQTD+RrJrU0D/AJClv/1zn/8AQK2ofxI+p04T+PD1R2lFFFfRH2wUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABXPeKB+5sD6TSD80roaw/Eq5soH/uXKf+PKwrnxSvSkcWPV8PM5Oiiivnz40KKKKACiiigAooooAKKKKACiiigAooooAKKKKAGsqupVhkH/ADmqDCe1lDRu6N1SSNmRiPqvNaNMkRZFKt07HuD6iqjKxpCbix0PiLxBAMC8Zx6Tokn6kbv1qyPFuu4x/oh9/Jb+jVhyRtGxVvwPYj1FMrqVaa2Z3xxNVLST+82ZfE/iCQEC5SMH/nlCgP5tk1mT3V3dNuubiaY9vNdmA+gPFQ0UpTlLdkyqzn8TbCiiioMwooooAKKKKACiiigAooooAKmgnMRweYyefY+oqGik1cTV9GawIIBByDyCO9LVC3n8s7HPyE8H+6f8Kv1i1Y5ZR5WFFFFIkK1fD4zqcR9IZj+gFZVbXhtd19M39y2b/wAedRW+HV6sfU68Gr14ep11FFFfQn2gUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABWZrse/TLo94zHJ/3y4zWnUN3F59rdw4z5kMiD6lTis6keaDRjXhz05R7pnntFJS182fDBRRRQAUUUUAFFFFABRRU1ra3F5MsMCbnPJJ4VF/vMfSmk27IqMXJ8sdyCrkGm6ncgGG1lKnozgIp+hfFdVYaLZWQV2UTXHUySAEKf9hTwK069KngW1ebPcoZQ2r1XbyRxo8Pawf4IR7GUZ/QUf8I9q/8Adg/7+/8A1q7Kit/qNLzOv+yaHn95xv8Awj2r/wB2D/v7/wDWo/4R7V/7sH/f3/61dlRR9RpeY/7Joef3nG/8I9q/92D/AL+//Wo/4R7V/wC7B/39/wDrV2VFH1Gl5h/ZNDz+84qXwzqsq7SsGeqnzeQfyqn/AMIpr/8Actv+/wB/9jXoNFUsHTXcqOWUY7XPPv8AhFNf/uW3/f7/AOxo/wCEU1/+5bf9/v8A7GvQaKf1Sn5lf2dR8zz7/hFNf/uW3/f7/wCxo/4RTX/7lt/3+/8Asa9Boo+qU/MP7Oo+Z59/wimv/wBy2/7/AH/2NH/CKa//AHLb/v8Af/Y16DRR9Up+Yf2dR8zz3/hFNf8A7lt/3+/+xqtP4f1+3BZ7J3UckwMkv6Id36V6XRSeDh0bJeW0ns2eQkMrFWBVlOGVgQwPuDzSV6jf6Vp2pIVuYVL4wsqfLKn0cc1wer6Ld6TIC3721dsRTgY5/uyDsf5/oOSrh5U9d0ebiMHOj726MqiiiuY4gooooAKtW8+3Ebn5eik/w+x9qq0UmrktJqzNeiqdtP0jc+yMf5GrlYtWOaUXF2Cuj8Lx/Nfy+ghjH/jzH+lc5XX+HItlgZCOZp5H+qrhB/I11YON6q8j0MshzYhPtdmzRRRXun1oUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQBwF/D9nvbyHGAkzlf91jvH86rVu+JbfZdQXAHE8exj/tx/wD1j+lYVfOVoclRxPiMVT9lWlDzCiiisjnCiiigAooooAVEeR0jRSzuwRFHUsxwBXdabYRafbrGMGVsNO/dn9PoO3/1657w7bCa8knYZW2TK+nmPkD9M111etgaSS9oz6PKcOlH2z3ewUUUV6R7gUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABUVxbwXUMtvOgeKVSrqe4Pce/pUtFG4mrqzPLdT0+XTLya1cllHzwuf8AlpE33T9ex+lUq7rxfZiWxivFH7y0kCsfWKUhTn6HFcLXi1qfs5tI+XxVH2NRxW3QKKKKxOYKKKKACrtvPuxG5+YfdJ/i9j71SopNXJlHmRrV6BYQ/Z7Ozh7pCgb/AHiMn9a4PRR9tvbO3flvMDv/ALUcfzmvRa7sDTteTPWyik1zTfp/X4BRRRXpnvBRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAGZrlt9p0+YqMyQYnT1+X7w/LNcVXpBAIIIyCMEHuDXA6hamzvLiDHyq26L3jblf8PwrysfT1U0fPZvRs1VXoyrRRRXmHghRRRQAUUUUAdV4ZQC0un7vcbT9FRf8a3qwPDDg213H3ScP+DoB/St+voML/CifZYC31eFgoooroO0KKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAoazGJdK1VD/z6zN+KLvH8q8vr07XJRFpGqOe9tIg+snyD+deY15mM+JHhZnb2kfQKKKK4jygooooAKKKUKzFVUEsxCqB1LE4AFAHW+DbPLXt+w4GLWEn14dyP/HRXY1T0yyXT7G0tRjdHGDIR/FI3zOfzq5Xt0YckEj6rDUvZUlEKKKK1OgKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKwvEdn5sEd4g+e3+WTHeJj1/A/wAzW7SOquro4BV1KsD0IIwRWdWmqkHFmGIoqtTdN9TziirV/ZvY3Utuc7Qd0TH+KM9D/Q/SqtfOSi4uzPiZxcJOMt0FFFFIkKKKKANbQLoW98I2OEul8rnoHByv9R+NdlXm4JBBBIIIII6gjnIrtdI1NL+EI5AuogBKvTeOm9R7969XA1lb2b+R9BlWJVvYy+Rp0UUV6Z74UUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRVW/vrXTraS5uGwqjCqPvSOeiKPU0m0ldilJRV2c/wCML1UgtrBT88zieUDtGn3Qfqf5VxVWL27nv7qe6nPzytnA6Io4VF9hVevFrVPaTcj5bE1vbVHMKKKKyOcKKKKACug8K6f9rvvtTrmGyw4z0advuj8Ov5VgokkjxxxqWkkZURR1ZmOABXp+k6emm2MFsMFwN87D+OVuWP8AQfSurDU+ed3sjvwND2lTmeyL1FFFesfRhRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAZetaf9utt0Y/0iDLxerj+JPx7VxdekVyuv6Z5Lm9hX91K379R/BIf4voe/v8AWvMxtC/7yPzPCzTCcy9vD5/5mDRRRXlHzoUUUUAFOjklhdJYnZJEOVZTgg02ii9tUNNp3R0tj4mtiUh1LEEh4WcA+RJ9e6n9PeuhjkilUPFIkiHo0bBlP0I4rzd0WRSrDg/mD6iqIa7s5P3U0sR6hoXZNw9flNelSxsrWkrnuYfNJpctRXPWKK8wGta6Bgajdfi4J/Mij+29e/6CNz/30v8AhXT9cj2O3+06f8rPT6K8w/tvXv8AoI3P/fS/4Uf23r3/AEEbn/vpf8KPrkezD+06f8rPT6K8w/tvXv8AoI3P/fS/4Uf23r3/AEEbn/vpf8KPrkezD+06f8rPT6K8w/tvXv8AoI3P/fS/4Uf23r3/AEEbn/vpf8KPrkezD+06f8rPT6K8w/tvXv8AoI3P/fS/4Uf23r3/AEEbn/vpf8KPrkezD+06f8rPT6K8w/tvXv8AoI3P/fS/4Uf23r3/AEEbn/vpf8KPrkezD+06f8rPT6K8w/tvXv8AoI3P/fS/4Uf23r3/AEEbn/vpf8KPrkezD+06f8rPT6CQASTgDkk15h/bevf9BG5/76H+FV5r2/ueLi6uJR6SSuy/985xSeMj0QnmcOkWd7qPiTSrEMiSC5uBwIoCCoP+3J90fqfauG1DUr3U5vOuX4XIijXIjiU9lB/U1Torkq15VN9jza+LqV9HouwUUUVgcoUUUUAFFFaWj6XLqt2sQytvHh7mQfwpn7oPqeg/PtVRi5OyKhBzkox3Zt+E9K3MdUnX5V3JZhh1b7rS/h0H412VNjjjhjjiiUJHGqoirwFVRgAU6vapU1Tjyo+poUVRgoIKKKK0NwooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACmuiSI8cihkdSrK3IIPBBp1FAbnD6ppsmnzYGWt5CTC57d9jH1FZ9eh3NvBdQyQTLujcc+oPZlPqK4jUNPn0+by5PmjbJhlA4dfQ+47ivExWG9m+aO35HyuPwLoPnh8L/Ap0UUVxHlBRRRQAUySNZVKt+B7g+op9FA9jKdGjYq3UdPQj1FNrTliWVcHgj7p9DWcysjFWGCP85raMrnTCXMNoooqiwooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiipbe3uLqaK3t4zJNKcIo/Uk9gO5o3BJt2Q60tLm+uIra3XdLIf+Aqo6ux9BXpmm6db6Zax20PJHzSyEfNLIerH+lV9G0eDSYNow91KAbibHU/3Ez/CO3+caleth6Hs1d7n0WDwvsVzS+J/gFFFFdR6AUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFQ3Ntb3cLwToGRvzU9mU+oqaik0mrMUoqSs9jhdR0y40+TDZeBj+6lA4P8Ast6H/P0o16LLFFNG8UqK8bjDKwyCK5PU9DmtN01sGltuSV6yRD39R7//AK68fEYRw96Gx8zjculSvOlrH8jGooorgPHCiiigAqKaFZV9HH3T/Q1LRRsNO2qMkhlJVhgg4IpK0J4RKMjhwOD6j0NUCCCQRgjgg9q2TudMZcyEoooqiwooooAKKKKACiiigAooooAKKKKACiiigAoorS0vR77VZMRLst1OJbhwdi+oX1PtTjFydkVCEpvlirsqWlpdX06W9tGXlb8FVe7Oewr0TR9GtdJhwMSXUgHnzEcnvtQdlH+faxp2m2WmQCG2Tk4MsjYMkrerH+Qq5Xq0MOqer3PoMLg1R96WsvyCiiiuo9AKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKAMXUdBt7ndNa7YZzyVx+6kPuB0PuK5a4trm1kMVxE0b9s9GHqrDg16HUc9vb3MZjnjSRD2YZx7g9a4q2DjU1jozysVlsK3vQ0f4HndFdDe+G3Xc9jJuHXyZThvor9Pz/OsGWGeBzHNG8bj+FwQfwryalGdN+8j52thqtB2mv8hlFFFZHOFV7iDzBvX746j+8P8asUU07DTad0ZFFXbiDdmRB838QH8XuPeqVbJ3OqMlJBRRRTKCiiigAooooAKKKKACiilAZmVVBZmOFVQSxPoAOaAEpyJJI6RxozyOcIiAszH0AHNb2n+FtTu9r3X+iQnnDjM7D2Tt+P5V2On6Tpumri2hAcjDyv80r/AFY/yGK6qeGnPV6I76GBqVNZaI5vSvCbtsn1T5V4ZbVD8x7/AL11/kPzrsI44oUSKJFSNBtREAVVA7ACnUV6VOlGmrRPco0IUVaCCiiitDcKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKjmgt7hDHPEkiHs6g/lmpKKTV9GJpNWZg3Xhq1fLWsrQt/cf54/wP3h+ZrFuNG1a3yTAZUH8UB3jH+7979K7iiuSpg6c9tDza2WUKmqVn5Hm5BUlWBVh1DAgj8DRXoctvazjE0MUg/wCmiK35E1ny+H9IkyVjeI/9MnYD8myK45YCa+F3PNqZRUXwST/A4yqdzB1kQe7qP5iuxk8Lx8+VeOPQSRhv1Uj+VVn8M6gPuT27fXep/kax+rVovY5fqGJg/h/I4yiuin8K6zu3QpbkHqBKBg+24VB/wi/iH/n3i/7/AMf+NV7Kp/Ky/q9b+R/cYlFbg8K+ID1igH1nX+gNTp4P1lvvzWaf8DkY/otNUaj6FLC1n9lnOUV10Xgt/wDlvqAHtDDn9Xb+laEPhHRY8GVrmcjrvk2KfwjAP61osLUfQ2jgK8t1Y4Hir1rpGr3mPs9nMVP8cg8uP/vp8V6Lb6ZpVpj7PZ28ZH8QQF/++my361creOD/AJmddPLP55fccdZ+DWO1r+6AHBMVsOfoZHH/ALLXS2Wl6Zp4xa20aNjBkI3SN9XbJ/WrlFdcKMIbI9GlhqVL4VqFFFFanQFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFAH/9k="
	DefaultGroupPhotoBase64  = "/9j/4AAQSkZJRgABAQEAAAAAAAD/2wBDAAYEBQYFBAYGBQYHBwYIChAKCgkJChQODwwQFxQYGBcUFhYaHSUfGhsjHBYWICwgIyYnKSopGR8tMC0oMCUoKSj/2wBDAQcHBwoIChMKChMoGhYaKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCgoKCj/wAARCAHkAeQDASIAAhEBAxEB/8QAHwAAAQUBAQEBAQEAAAAAAAAAAAECAwQFBgcICQoL/8QAtRAAAgEDAwIEAwUFBAQAAAF9AQIDAAQRBRIhMUEGE1FhByJxFDKBkaEII0KxwRVS0fAkM2JyggkKFhcYGRolJicoKSo0NTY3ODk6Q0RFRkdISUpTVFVWV1hZWmNkZWZnaGlqc3R1dnd4eXqDhIWGh4iJipKTlJWWl5iZmqKjpKWmp6ipqrKztLW2t7i5usLDxMXGx8jJytLT1NXW19jZ2uHi4+Tl5ufo6erx8vP09fb3+Pn6/8QAHwEAAwEBAQEBAQEBAQAAAAAAAAECAwQFBgcICQoL/8QAtREAAgECBAQDBAcFBAQAAQJ3AAECAxEEBSExBhJBUQdhcRMiMoEIFEKRobHBCSMzUvAVYnLRChYkNOEl8RcYGRomJygpKjU2Nzg5OkNERUZHSElKU1RVVldYWVpjZGVmZ2hpanN0dXZ3eHl6goOEhYaHiImKkpOUlZaXmJmaoqOkpaanqKmqsrO0tba3uLm6wsPExcbHyMnK0tPU1dbX2Nna4uPk5ebn6Onq8vP09fb3+Pn6/9oADAMBAAIRAxEAPwD6i800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800eaaZRQA/zTR5pplFAD/NNHmmmUUAP800UyigBaKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKPwNABRQOegNB460AFFIGz0paACikyO/H1pRg9CKACigg+hooAKKQnFGfSgBaKTI9fwozx7+lAC0UDmigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAoopCcCgBaKQMDwOT6UMwHX73p3oAWkbOPlzn9KAf73ynrg1y/ivx74f8LQs+qahAjgf6veAxoA6f5v485/2KbM6RoWlby0Xks3Ar5j8a/tNRqssHhm0YNyBLMFYH6YNeJeIviv4r1xnNxqU0St/DDIyD8s0AfcWr/EDwtpKt9s1qxRl6qJgDXEap+0H4QsA3kPLcsP+ebIc/rXw/dX1zdsWubiWVj3dy1QbvagD6x1L9qGzDEWWmS+xkjH/AMVWJP8AtQ6kCfI0+1x2zF/9lXzTu/yaC2ew/KgD6M/4aj18H/jxs8f9cj/8VU0P7Uer7v3+n2uP9mI//FV82ZooA+q7D9qOIsBe6a3/AACMf/FV2GjftG+FbxQLqK5gY9SxQD+dfEmaAcUAfono/wAUvB2rFBBrFmjn+Fplz/Ouvs7u2vYvMs7iKaP++jZr8wobiSFt0TvG/qpxXTaD4/8AEmiSK1nqt0QP4HmYr+WaAP0ewc5+bH86BXyJ4J/aV1Ox2xeIbcXEPTMKYb8y1e8+Dfi74W8UBRDex20rdI5pBu/SgD0OikVg6hoyGU9CO9HTrwPWgBaKMgdTj0zR9OaACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiig8DJ6UAFHB60jMq4yevSo7idLaF5bghIkGWY9qAJDy20qc9iOK5rxd410PwpZyTarewoygkIThifT9K8h+Lnx7tNFjm07wwy3F0cq03UL+BFfKniXxLqniK8a51S6eWRjnAJC/lQB7V8Sv2hNT1jzrTQF+y23KiRgNzDnkEGvCtS1W/1OZpL+7nnZjk+ZIWH6mqG7HSgtmgBxHzYBB+lMbrS7qSgBKKKKACiiigAooooAKKKKACnqAV54NMp2c9aAFzxzU9vdTWrq9rNJE47oxH8qrZp2+gD134d/HDxD4WdYbmY3lkOoky7fmT719SfD74ueHPGUKJHcpa3rf8u0rgs30xX5/bsnnpVuxvrqznE1rK8bqchkYqf0oA/TrBzgcDuG5Ipw46V8k/CH4/3VjJDpvig+bb/dWXgEfU8k19TaHrNjrunx3mlzrNE4BBWgDRopAcnHVh2pfrQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFH8u9ABR+GT2ppJ/hGayvE+v6f4d0qS+1GUJGgyPrQBLretWWiafJd6hMsccYyzGvj74yfG+88SXEthojmHThwHH8Y/LPrXOfGT4o6h411V4o3MWnocJGD16ew7ivLdxHTrQA+STzGLPudj1JPWmPjsMUbsdBikLZoAbRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFPBBwDwKZS5oAeDx64716J8Lvifqvgu+Xy5Wksi3zxE9uO5+lec5xS7uvHfNAH6NfD3xxpfjfR4rmwlXzdo3xZ5U4H+NdcvTA4x1r83vAfjPUfB+tRXunysoDDevZhnOP0r7o+Fvj+w8caPFPFIovFUCRO+cDP6mgDuc5+lFI2eMjv+VLQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRQBk4oAKM45/Sj+En0psjrGm6TG0DJoApatqEOl6fNeXcixRxjLEnrXw38bfifdeM9WltrV2TS42wi/3untnqK7T9pL4pPq17LoelyEWicSMp+90P8xXzuxJ5bmgA6txxTWGOnSkzQxzQAlFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAo5NdX8PfGF/4O16C+sJCArAyJnhgDnHSuUp+crjjr1oA/Rv4deMbHxp4fgvrFwz4Alj7qwAyfzNdWK+Avgt4/ufBPiSF0c/ZZWCzJnhlznFfduiavbazptvfWjBoZVBJHY45oA0aKBzRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFH069qKRulACMN23HTODXj/7QvxCHhTw5LZ2Mw/tC4XauG5HQ16lrmpw6Npdxe3bbYYU3k1+fXxW8W3Hi3xVdXsjHyVcpGueAASM0AcldXEl1cSSzHdI7bifWoGx26UbvSkJzQAlFFFABRRRQAUUUoGaAEoqTZ+P0qW3sri6bbbwySH0Vc0AVqK1z4a1oJvOl3oX1MLYrPuLWe2bbPE8bejDFAEFFO20YoAbRTsUlACUUtOC55oAZRTsUYoAbRTsfWjH4UANopcUlABRRRQAtLjim07PNADs8DHX1r6Y/Ze+JDQXR0HVpv3EmFi3HgHP+Ar5kzV3SL+XTb+G5t3ZHjbIYHFAH6eZB27R8uMgilrhPg54yj8X+ELeYspuol2yAH04H8q7rP8A9agApaGBBHT8KKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKDQAUhAPXP4UhOPyqtql4llYTXLnCRpuyaAPn39qvxw+n6UuhWcpEk4xLg8hSOO/tXyLK2455x7+tdl8WvEUviTxpf3UjlkRzEvPGFY1xRoASiiigAooooAKKKco9aAG1a0+zmvrhILaNpZXOAiDJNRpFvIVfvHpX1j+zP8ACuCK1XXtYty0jcwq4+hB5FAGD8Kf2eJr+KHUfE7tDbthhApKsR7gj3r6J0H4ceF9FgWO30i0cqOHeFSx/HFdciLGgCgBVGAo7U9RxQBl/wBg6SV2HT7Qp/dMYrnPEnww8Ka7AUn0q1hbH34olDfniu4xSMoPrQB8Y/Fb4AX2hpJfeHQ91aDkxctIOnoMeteBXUUkM7xzIYpFPKkYxX6kTQpNGySKGVhgg18mftN/CyKxf+3dFgKxsczKo4BJA7D2oA+ZPegU7AIJ7UKgbPOPb1oAbWromhajrlylvpdpNcSscYjUn+Vbnw28E3njPX4bG0B2Fh5jYPyrkAn9a+6Ph38ONF8HaZDFa2sb3IUb5nUFt2BnBxntQB8seHf2cvFOqxJNcTWtmuMlJ9yt/Ktq8/Zd15IC0OpWJYdizf8AxNfYmwccdKXaKAPzu8YfCnxR4YJN1YyyxD/lrFGxX88VwTAo3zD256iv1GvrG2v4DFdwRzRkYw6gj9a+WPj98FY7SKfW/DkJCLzJCo+g4AGPWgD5eIx6Uyp3jIbaSPl4JqGgBKKKKACiiigAqTAyPSo6duOMUAe4fsy+Nn0LxQmn3Em20uDg5PA6n1r7WRgVDHBRhkEV+Yuk30ljqENxExVkbIIOK/Qv4T+Il8TeC7S6dg0u3D4PuQP5UAdiMDvnPSlpMEYz+FKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKO1FFADcZ6+leVftFeJDoXgW5hhfbNco0anPcqa9X25znvyK+Rv2vPEX2jVLXSI3/wBViQgfRhQB85zSNNJI7cszFmPqTURoyaKAEooooAKKKKACnpnoKZSrQB23wn0AeIfGenWsgJh85d/0yK/Q7RrKLT9MtbSBQiwxqgAGM4GK+OP2S9PS78YTSyLkxx7l9iGWvtNFwOKAHY5zRS0UAFFFFABWH4w0mHWNCu7S5QOjoQAR3wcVuUyRQyMD6YoA/M7xxozeHvFF/prAgW8hQe9Y9upllVUGWJwBXrP7Ttill8QnZFwZgzn35rzvwbbi78SWETDhplGPxFAH2h+zf4Ki0DwjHe3EAF7dgSByOdhANezCsjwrALXw3psQ4CQIuPwrYBzQAUUUUAFU9RtYr21khnUMrAgg8irlNbAPNAH59fHbwgfCvjO5WGMpa3Dbolx2AGf1NeZmvqr9sbT0K2V5j50BAI9ytfKtACUUtJQAUUUUAFFFFACjrX1V+yP4mLNcaNM/XBQE/wC8TXyrXpHwK146D46sZ2farEqc+4I/rQB+gXcg/hRTUYOqupyCMinUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUZxRRQAyY7Incn7q5r8+vjnqZ1Xx/fzE58tmi/Jmr7y8T3X2PQb64zjZCxz+FfnJ4vumvPE2pzMclriQ5/4EaAMWilooASiiigAooooAKVaSnJ1/lQB9Cfsh3ccPiy4jkOC8WB9dy19mLkV+d3wW1/8AsDx1YTyPthaVRJ9NwzX6E6fcpd2MFxCwZJUV1+hGaALJGaXFNz8vXBNKOlAC4oxRSE84oAXFNk4RvpS5OeKzPEOoJpukXNzMwVUjY5P0oA+Jv2pLtLr4glUOfJVlP515v4InW38T6dK3AWZCfzFXPiPrba/4v1K9zuWSUsh9sCubtZDDcJKvBVgaAP048LyrceH9PmU5DwIR+Vagryr9nzxZF4j8E20RlBntVEZXvgKOf1r1Pf270APoxSc00HkjOTQA/FNxkEGkL45NRXMwhhaRiAijJNAHzJ+2Jdxi1s7bPzOCcfRlr5PNevftG+K08R+M3t4JPMgtCVVh3yFNeQn2oASilpKACiiigAooooAUVo6FP5GrWsmcbXBzWdT4mKyIR2NAH6VeBr/+0/CenXmcmRCfyJFbteafs+akNQ+HOnKx3NAhB9ss1el0AFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUHpRRQBx/wAWZ/s/w/1ZxwfIf/0E1+dt+2++uG/vOx/Wv0B+Oz+X8NtWI4PkP/6Ca/PmUlpGY9zQAyikooAKKKKACiiigApy02loAmhkaORXTgqc19mfs3fE231jR49E1GYJdwgLGSeo4AFfFuTkH0q/omqXWkajFe2ErR3EbBlZfWgD9QV5XnkU6vm74T/tC2d5bwaf4mzFOoC+dgtnoOe1e+6brumajbpLZ39vIrcjEi5/nQBqUjccmo/tEZGTLGB67hWZq3iXSNKhaS9v7dFAzjzFz+WaANZ2CKSTgAZJr5k/aa+J8MdodC0mbdI3+sK9sH/A1U+Ln7Qsbwz6b4WZhJ91psFT29Rivl6+vrm+vJLq6laS4kOXc9TQBG3sfp9KaOKbuIOc80oJJzk5PWgD0H4P+P7nwP4iiuEc/ZWIWVf7y5Ge3tX3Z4Q8Wab4o0uG80+4Q70BMeeQcD8e9fmkDgn3710ng/xlrXhO8W40e8kiIPKjAB/SgD9K+AB70EDPue9fJPhr9p+8gjWLWtNikOMGXzGJP4AVv3X7UlisJ+zacryY4Dbx/SgD6UldYl3Oyqi8kk4r56+P3xht9LsZtH0KcSX0gwzr0Xp7Y6V4344+PfiXxJFJbWrfYLZuCIn3Z/MV5BNNJNM0srlnbkt60ALJI0rM0hJLnJNQtTlHXnBplACUUtJQAUUUUAFFFFAC0vTFNp39KAPtP9ku483wfeRsfusmP/Hq92r52/Y6l36HqSk5wyY/Jq+iTQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQB538e13fDXVsf88H/9BNfn3JwSPev0R+MkH2j4d6sMZxA//oJr88rxdl1KvoxH60AQUUtJQAUUUUAFFFFABRRTlA75oAbUkbYBx19aML3z7Vf0fRdR1a4EWm2k08jcARoW/lQBSY8Ank9609L8R6xpAA03UJrfByAhHFeo+Ff2e/FesIss4htY26rKWVvyxXoOn/stoyg3mpSK3cRuP8KAPCD8UPGhj2N4jvivpkf4Vg6rrupaw27VL6a4Pq9fVB/ZZ0nZxql5u9yv+FZWofstBYz9g1J2ft5jjH8qAPlwMij5Ru9z2qNzls5z716/4r+Afi3QFaQRRXkQ6C23O38q8uv9JvdOmMN/bS20g7SqV/nQBn1NFHvGBksegxTVXd1wO1fR/wCzp8LtE15Bqeq3UFw6EYtdyt6HkUAeU+C/hh4j8WToun2ckcRPMkylF/A4969z8MfsvQhUk17UpQ/UxxhWWvpTTbG00y0S1sYUhhTgKowBV8YIoA8esf2fvBlsg86yjuGA/jTr+tW5PgT4HkTH9j2yH1C//Xr1bAPajaPQUAeCa9+zV4avEP2GeW0bsI0X+teQeNP2c/EGjRtPpMi3duvPLDf+QFfbWBTeNwB5oA/MLU9JvdNmaHUbaWCYHpIhXP51muPmr9EfiN8MtE8ZWkhuLWJLzHE20bvz/Cvir4nfDnU/BGrSRXMbtabv3c2DgjjqcetAHBUlTFAck8HuKiPWgBKKWkoAKKKKACndaSlz0oA+u/2N0I0bUz/tJ/Jq+ju1eA/siW/l+F7+Xplk/H71e/GgAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACkPNLRQBz/ju1+2eEtStxzugYfpX5y69D9n1q/iP8E7r+TGv0zvYRNazoed0ZXFfnb8V9POn+N9TjK7d0zsBjHBY0AcdSUUUAFFFFABRRSr1oASnxBiwCjJPAFOVRuweh5FfQP7PHwlbxDcR6zrMJWxjIZFZeH6EdsUAZXwh+CF/4vaK81ZZLTTMgkkFXYcdOMdDX1n4P8BaD4Vs44tP0+EyR8CYxjzDjHU49q6XT7O3srNLaziWKJBhVUAVaXpQBGucZwAKkHPbFLxRQAn0NNO4HjFPooAiYAggrlT1FcT45+HHh3xVaOl5YRLO44ljjUOD9cV3dNYenWgD4J+Lfwc1bwTM9xbo11pucrIgLFR7nGK5L4f8AjTUvCGrxXdjOwUMC6bjhhkZ4z7V+imtaXa6vYy2d9AkkMikHcoIr4n+PPwpl8I6s+oafGTpsrZ4HCEk8dMYwKAPq/wCGfjyw8b6BFdWjoLpVAmiyN2cDOBn3ruE+6Oor89fg346ufB3im3kEp+ySSBZhnjbkZxz7V996LqcOq6XbX1s4eGaNXGDnqM0AaGKXFNY8Uq49aAFxTOjf1p+aKAG/liuV8feE9P8AF2i3FlfxI7EfIxAJU9sfjXWcYqNwMZAByaAPzc+IvhO68H+IrjTrpW2qx8tyPvKO9cmfvV9pftS+CV1fw+dWtYgbm36lRzt5J7e1fFx64AoASkpaSgAooooAKegyw9zTat6ZD599BF/eYCgD7i/Zm0w2Xw/ilx/x8AN+RavXfauT+Fdh/Z3gHSICNrJGcjp/Ea6ygAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACjntRR0oAPlPXsMGviT9qjQG0/xt9uUYhnQAcd8sa+2cZ/nXgv7WHh46h4WivkTP2Zi7EDsFNAHxhRTz3yPpTTQAlFFFABTlptOUZOPWgDtPhZ4Wl8WeLLS0iQtFvDSYHRQRmv0I8NaTBoej22n2kSpDAgjGBjdjvXgX7I/hRLfSbnWZ0HmswVMjsV/+tX0ipz1oAQjHH8qcvSlooAMUYoooAMUYoooAMUnTpS0UANHpkZrnfHfh218T+HrvT7uMMJEYKccg4Iz+tdJxSNjv6UAfml478PS+FvE93pzBlWJ28snuoJAP6V9Q/so+NTqGkyaJdS+ZNCC6ZOcD5QBXN/te+FhE1trUCAbmEbFRj+8a8o+AmvNonj/T2DERSSqrc9RmgD9Bcng49jTgBUNrKJ7aKZejqGH4ip6ADFGKKKADFJ9KWigDD8X2K6joF9b7A5eJkwRnqDX5yeMdOOk+JtRswuFhmZK/TO4AMEg9VNfnv8ebcW/xD1MqAN0rHA+tAHnOABTaXpSUAFFFFAC11nw20h9a8V2FtGMnfk/hzXJ19BfsoeHDfeKv7SdMxQDqR6qwoA+wbGBbW0igQYCKBip6UENkjtSUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUHpRRQAxvb0rF8aaRHrfhm9sJlDLLER+dbtBGRjrQB+Z3izTX0nX76zkXb5cz7fpuOKxjX0N+1Z4O/s/W49atoz5U+EYjsQCSa+e3GMZ60AMooooAKs6fH515DH/AHnA/Wq1afh0BtatAenmL/MUAfoP8GtLTS/h5pEYGHeAM3uea7heRz171geBgI/COlLn5fJH8zW+CO1ADsUYpM+9GaAFxRijNGaADFGKM0ZoAMUYozRmgAxTWGeKdmkz+FAHlX7ROlpqHw9v3cZ8mJnX6hTXwx4euHs9ZtXTgrKOa/Qn4up5vw/1hcf8u7/+gmvztuJGg1CVkO10kJBx70AfpX4PuluvC+lzAj/j2jB+u0VtZFfn1pvxr8ZadYwWlrqRSGLAA8tTxjHpVk/Hnx3/ANBc/wDflP8ACgD784o4r4C/4Xz47/6C5/78p/hS/wDC+fHf/QXP/fpP8KAPvzijivgP/hfPjv8A6C5/79J/hR/wvrx3/wBBc/8AfpP8KAPvmbHkv/umvz9/aEBHxEvvTe386sH48eOmBB1YkHg/uk/wrgPEWu3viDUJL3U5fMuHJJbAH8qAMo02nUlACUtJUnopoAIUaSVUUZJOK+8P2dPDY0LwNFMyYluBknHoT/jXyZ8GfC7+KfGVpbmMmFWyx9OD/hX6AWNvHbWcVrAu0IoHFAFkDgkdKWk7jHaloAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKRunXFLSH36UAcj8TvDEXizwpe6eUDSNEdhPYmvz48R6bNpOq3NlcoVlikZefQHiv01xt2g9Sa+V/2pvh4UkPiOwjLcYmCjsB/iaAPl6kqTgMM8jvmkIwSKAGVZ0+5Npdxzqu5kYMBn0qtRQB71pP7Ruvafp8FpFZoyQptGZcf+y1Z/wCGnfEP/Pin/f3/AOxr58ooA+g/+GnfEP8Az4p/39/+xpf+GnfEP/Pin/f3/wCxr57ooA+hP+GnfEP/AD4R/wDf3/7Gj/hp3xD/AM+Ef/f3/wCxr57ooA+hP+GnfEP/AD4R/wDf3/7Gj/hp3xD/AM+Ef/f3/wCxr57ooA+hP+GnfEP/AD4R/wDf3/7Gj/hp3xD/AM+Ef/f3/wCxr57ooA+hP+GnfEP/AD4R/wDf3/7Gj/hpvxCf+XJPp5v/ANjXz3RQB7j4i/aE1zXNIuLG4tVRJVKnEmeo+leKzSmad3PV2LH8agooAeTz9KbmkooAXPvRSUUALRSUUAOpeG6DFMooAeT+FNop3vnpQA2nxo0kiqvJPSkxxz3r1L4C+A5PGHiiLzUP2OAhpCRwRyKAPob9mPwR/Yfhs6pdR4nuPu54IwT/AI17f823gAVFaQLaWsVtEoEcahR+AqagBOB93v1paKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACgYzz0oooAQ9CT1HSqGuaZbaxpk1ldxCSGVdpBFaFIc9jg0Afnv8XPA134O8STwtEwtXbdG2OPX+tcAelfoj8UvBFj428PzW9ygW5A/dyYGQeOn5V8FeMPDd/wCGdYmsNQhaN0bg4IDCgDBop2MNzxQ56evegBlFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAopRjHOetJVuwtZ7+6jtbaNnkkO1VUZJNAF/wzoV1r+rW9jaRu7SsFG0Zr73+E/gqDwZ4bht4o1W7mUGRx15ANcT+z38K4vCumx6tq0YfUplDIrDPlDggjjINe39aAEGT1JyKWiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACj+faiigBvTquf6V5h8ZPhdaeNdId4URNQQZWTGCenfGe1eo0hHGeTj0oA/M/wAUaDfeHdWkstRgkikQ4+dSM1jHtX3/APFn4Xab45095PLSK+AykqADP1OM9q+J/Gng/VvCGqSWmqW7JtOBIVIVvpn60Acxg+lGKkww7ZB6UjgjqMUAR0UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRT1BPHA96AG4owfSnqOvc5q9o+l3er3qWtjC807sAEQZNAFSztZru5jgt42eVztVVGSTX11+z78HE0qKHXPEEQe5IDRRMPu9COCKt/Av4KQaDFFq/iGJZb4gMsLLnZ0PII6176ihcAKEUDCqBgCgBAAoAAwBwMdv/rU8UdeDwRzRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFBz260UUAIdwxsK+4Irl/HHgvSvGGnSW1/bL5pGEk2jI/HGa6mjBI4/OgD4N+Kvwe1jwbcyTQxvc6fnKyIDhR7k15U4I6544r9Pryyt76B4LqFJ4GBDB1B/nXgHxT/Z7s9XM194bcW9xgt5RyQevAAwKAPj3GKMV0finwhq/hi7eDVrOWAocBmHDe4rn+tADMUU84BxkEdcimHrQAlFFFABRRRQAUUUUAFFFFABS4z0pKeBu56CgBtGM04+1KcgAnv0oAYAScYp64Ix1PtV7SdKvNWu1trCB55mOAEr6C+GX7O99fNFe+KW+yw5DG2IKu34jigDx3wF4E1fxlqKW+m20hiz80m3IWvsn4U/CTS/BViklxGlxqBGWdhnB46ZGR0rt/Dvh7S/DlnHaaXaRwIowDtG/8Tjmtn680ANxnGR8g4AHBpR6dvelooAP50UUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUhAPUH86WigBAWPDfd9BSHcB8pwv92nUUAZGv8Ah3S/EFo1vqlpG8bDB4G7868F8e/s2WV15lx4Zm8iQ5IibLZPPqa+kaM469KAPzw8YfC7xR4XdzqGnyCEdJAQc/ka4iSKRGIdGXHHIr9QJYYbmNo5IkljPUMK4jxJ8KPCWvLIbzTFWRv41dh+gNAH55UYr608Q/swWdxufSNTMA7J5Wf1LVwOr/s4eKbRGNqRcgdOVXP60AeE0V6BqPwk8YWLHztKIx3Ein+tY1x4J8QQkiSwlyOuBQBy9LW4fCutZx/Z83/fNSw+DddmbEenzZ+lAHPUV3Fj8LPFt6wEWmNj3cCux0X9nnxffKrTW4gU996H+tAHi2DjNOVWPCgn6CvqPQf2XZPMR9W1Xg9U8r/Bq9T8LfA7wfoZDNaC4uR/y0LMP0zQB8W+GvBeu+I5RFpVhJKT9B/OvcvAv7Nl5O6zeJJxAvUxbeT+INfU2nadZadD5VnaxxgdMCreaAOW8H+AtA8J2qxaXZJuHV3+Yn8/rXUkZGAMe9LRQAgX0OPXPOaUDHvRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUUUUAFFFFABRRRQAUe2PxoooATA7jd+lKwBGB09KKKAGjP8XIp6nb0/KkooATG772PypBGueQp9top1FACbIh0hT8qTav/PNB/wABFOooATGPuhR+FA/OlooAQg+v4Uc46cf3aWigBAB3FLx2oooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACiiigAooooAKKKKACik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5o5oAWik5ooAs4FGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFGBRRQAYFFFFAH/9k="
	ErrChatParticipantNumber = errors.New("invalid chat participant number")
	ErrUserNoChat            = errors.New("user doesn't have any chat")
	ErrMessageHaveNoComments = errors.New("message don't have any comments")
	ErrUpdateMessageStatus   = errors.New("unable to update message status")
)

/*
User represent a user entity:
UsrId is the unique user id,
UserName is the name of the user,
UserPhoto  is the photo of the user is stored as a string in base64 format
*/
type User struct {
	UsrId     string `json:"usrId"`     // Unique user id
	UserName  string `json:"userName"`  // name of the user
	UserPhoto string `json:"userPhoto"` // Propic of the user
}

/*
Chat represent a chat entity, which can be either a group or a one-to-one chat:
ChatId is the unique chat id,
IsGroup indicate if the chat is a group,
ChatName optional value, which can be the group name or the other username,
ChatPhoto optional value, which can be the group photo or the other user propic,
Participants array that contain all the UsrId of that chat
*/
type Chat struct {
	ChatId       int      `json:"chatId"`       // Unique chat id
	IsGroup      bool     `json:"isGroup"`      // Indicate if the chat is a group or a 1to1
	ChatName     string   `json:"chatName"`     // Group name, or other username
	ChatPhoto    string   `json:"chatPhoto"`    // Group photo, or other user propic
	Participants []string `json:"participants"` // Array that contain all the user id participating in the chat
}

/*
Message represent a message entity:
MsgId is the unique chat id,
SenderId is the user id that sended the message,
ContentType	indicate if the content of the message is a photo or a text,
Content	is the content of the message which can be either a photo or a text,
DeliveryStatus indicate the status of the message, if sent, read, or in waiting to be received,
Timestamp is the date when the message is sent by the user,
Comments array of Comment is the array of reaction of the message leaved by other users
IsForwarded boolean value that indicate if the message is forwarded or not
*/
type Message struct {
	MsgId          int       `json:"msgId"`          // Unique message id
	SenderId       string    `json:"senderId"`       // User id of the user that send the message
	ContentType    string    `json:"contentType"`    // Define the type of the content if text OR photo
	Content        string    `json:"content"`        // Content of the message which can be text or a photo as a string in base64
	DeliveryStatus string    `json:"deliveryStatus"` // Indicate the status of the message
	Timestamp      string    `json:"timestamp"`      // Date when the message is sent
	Comments       []Comment `json:"comments"`       // Array of Comment that store the reaction of other users
	IsForwarded    bool      `json:"isForwarded"`    // Bool value that say if the message is forwarded or not
}

/*
Comment represent a comment entity:
CommenterId is the id of the user that leave the coment,
Content is the content of the comment, that can be every emoji
*/
type Comment struct {
	CommentId   int    `json:"commentId"`
	CommenterId string `json:"commenterId"` // User id of the commenter
	Content     string `json:"content"`     // Content that can be an emoji
}

// AppDatabase is the high level interface for the DB
type AppDatabase interface {
	// User operations

	// InsertNewUser User, add a new user in the database
	InsertNewUser(userName string) (User, error)
	// GetUsrIdByName string, retrive the User.UsrId of the user by passing its username
	GetUsrIdByName(userName string) (string, error)
	// SetUserName error, update the name of a user, by passing its usrId and its newName
	SetUserName(usrId string, newName string) error
	// SetUserPhoto update the user propic, the function receive the user id and the new propic as a string in base64 format
	SetUserPhoto(usrId string, newPhotoData []byte) error
	// GetUserInfo User, search in the database a user with the usrId passed in the fuction, and retrive it info
	GetUserInfo(usrId string) (User, error)
	// GetUserNameById string, retrive the name of an user by its id
	GetUserNameById(usrId string) (string, error)
	// GetUsers User, get an array of all the users present in the db
	GetUsers() ([]User, error)
	// UsrIdExist bool, check if a user in present in the db by its user id
	UsrIdExist(usrId string) (bool, error)

	// Chat operations

	// GetUserChats Chat, retrive the chats of a user by passing its usrId
	GetUserChats(usrId string) ([]Chat, error)
	// InsertNewChat int, add a new chat in the db, the function receive an array of users that are in the chat
	InsertNewChat(participants []string, chatName string, chatPhotoData []byte, isGroup bool) (int, error)
	// DeleteChat error, remove a chat from the db, also remove all the message of that chat from the db
	DeleteChat(chatId int) error
	// GetChatInfo Chat, retrive all the info of a chat from the db
	GetChatInfo(chatId int) (Chat, error)
	// RemoveUserFromChat error, remove the associations betwheen a user and a chat
	RemoveUserFromChat(usrId string, chatId int) error
	// InsertUserInChat error, make the relation usrId <-> chatId
	InsertUserInChat(usrId string, chatId int) error
	// GetChatPartecipants string, retrive all the user id of all the users in a chat
	GetChatPartecipants(chatId int) ([]string, error)
	// GetChatParticipantsInfo []User, retrive all info of the participants of a chat
	GetChatParticipantsInfo(chatId int) ([]User, error)
	// CheckIfUserIsParticipant bool, check if exist the relation between the chatId and usrId given in input
	CheckIfUserIsParticipant(chatId int, userId string) (bool, error)
	// SetGroupName error, update the name of a group chat
	SetGroupName(chatId int, newName string) error
	// SetGroupPhoto error, update the group photo
	SetGroupPhoto(chatId int, newPhotoData []byte) error
	// IsAGroup bool, check if the chat is a group chat or not
	IsAGroup(chatId int) (bool, error)

	// Message operations

	// GetChatMessages Message, retrive all the messages of a chat by passing the chat id
	GetChatMessages(chatId int, usrId string) ([]Message, error)
	// InsertMessage error, insert a message in the database
	InsertMessage(message Message, chatId int) error
	// RemoveMessage error, remove a message from the database
	RemoveMessage(msgId int, chatId int) error
	// ForwardMessage error, forward an existing message with the msgId gived in input to another chat
	ForwardMessage(forwarderId string, msgId int, chatIdToForwatd int) error
	// UpdateMessageDeliveryStatusToRead error, update the delivery status of a message (And all its previus) to read, for the specified user
	UpdateMessageDeliveryStatusToRead(msgId int, chatId int, usrId string) error
	// GetMessageComments []Comment, get all the comment of a message by its msgId
	GetMessageComments(msgId int) ([]Comment, error)
	// CommentMessage error, comment a message
	CommentMessage(msgId int, commenterId string, content string) error
	// UncommentMessage error, remove a comment from a message by the commenterId of the message
	UncommentMessage(commentId int) error
	// GetMessageById Message, retrive a message from the database by its msgId
	GetMessageById(msgId int) (Message, error)
	// GetSenderIdByMsgId string, retrive the user id of the sender of the message by its msgId
	GetSenderIdByMsgId(msgId int) (string, error)
	// CheckCommentAuthor bool, check if the user is the author of a comment
	CheckCommentAuthor(commentId int, usrId string) (bool, error)

	// Ping error, verify the connection of the db
	Ping() error
}

type appdbimpl struct {
	c *sql.DB
}

// New returns a new instance of AppDatabase based on the SQLite connection `db`.
// `db` is required - an error will be returned if `db` is `nil`.
func New(db *sql.DB) (AppDatabase, error) {
	if db == nil {
		return nil, errors.New("database is required when building a AppDatabase")
	}

	// Check if users_table exists. If not, the database is empty, and we need to create the structure
	var tableName string
	err := db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='users_table';`).Scan(&tableName)
	if errors.Is(err, sql.ErrNoRows) {
		sqlStmt := `CREATE TABLE users_table(
    			usrId TEXT PRIMARY KEY NOT NULL, 
    			userName TEXT NOT NULL, 
    			userPhoto BLOB NOT NULL DEFAULT ''
        );`
		_, err = db.Exec(sqlStmt)
		if err != nil {
			return nil, fmt.Errorf("error creating database structure: %w", err)
		}
	}

	// Check for chats_table
	tableName = ""
	err = db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='chats_table';`).Scan(&tableName)
	if errors.Is(err, sql.ErrNoRows) {
		sqlStmt := `CREATE TABLE chats_table(
    			chatId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    			isGroup INTEGER NOT NULL CHECK (isGroup IN (0, 1)), 
    			chatName TEXT, 
    			chatPhoto BLOB
        );`
		_, err = db.Exec(sqlStmt)
		if err != nil {
			return nil, fmt.Errorf("error creating database structure: %w", err)
		}
	}

	// Check for chat_participants_table
	tableName = ""
	err = db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='chat_participants_table';`).Scan(&tableName)
	if errors.Is(err, sql.ErrNoRows) {
		sqlStmt := `CREATE TABLE chat_participants_table(
    			chatId INTEGER, 
    			usrId TEXT, 
    			FOREIGN KEY (chatId) REFERENCES chats_table(chatId) ON DELETE CASCADE, 
    			FOREIGN KEY (usrId) REFERENCES users_table(usrId) ON DELETE CASCADE, 
    			PRIMARY KEY (chatId, usrId)
        );`
		_, err = db.Exec(sqlStmt)
		if err != nil {
			return nil, fmt.Errorf("error creating database structure: %w", err)
		}
	}

	// Check for chat_messages_table
	tableName = ""
	err = db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='chat_messages_table';`).Scan(&tableName)
	if errors.Is(err, sql.ErrNoRows) {
		sqlStmt := `CREATE TABLE chat_messages_table(
    			msgId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, 
    			senderId TEXT, 
    			chatId INTEGER, 
    			contentType TEXT NOT NULL CHECK (contentType IN ('text', 'photo')), 
    			content BLOB,
				deliveryStatus TEXT NOT NULL CHECK (deliveryStatus IN ('sent', 'received', 'read')),
    			timestamp DATETIME DEFAULT CURRENT_TIMESTAMP,
    			isForwarded INTEGER NOT NULL CHECK (isForwarded IN (0, 1)),
    			FOREIGN KEY (senderId) REFERENCES users_table(usrId) ON DELETE CASCADE, 
    			FOREIGN KEY (chatId) REFERENCES chats_table(chatId) On DELETE CASCADE
        );`
		_, err = db.Exec(sqlStmt)
		if err != nil {
			return nil, fmt.Errorf("error creating database structure: %w", err)
		}
	}

	// Check for message_comments_table
	tableName = ""
	err = db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='message_comments_table';`).Scan(&tableName)
	if errors.Is(err, sql.ErrNoRows) {
		sqlStmt := `CREATE TABLE message_comments_table(
    			commentId INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
    			msgId INTEGER, 
    			commenterId TEXT, 
    			content TEXT NOT NULL,
    			FOREIGN KEY (commenterId) REFERENCES users_table(usrId) ON DELETE CASCADE, 
    			FOREIGN KEY (msgId) REFERENCES chat_messages_table(msgId) ON DELETE CASCADE,
    			CONSTRAINT unique_comment UNIQUE (msgId, commenterId)
        );`
		_, err = db.Exec(sqlStmt)
		if err != nil {
			return nil, fmt.Errorf("error creating database structure: %w", err)
		}
	}

	// Check for message_status_table
	tableName = ""
	err = db.QueryRow(`SELECT name FROM sqlite_master WHERE type='table' AND name='message_status_table';`).Scan(&tableName)
	if errors.Is(err, sql.ErrNoRows) {
		sqlStmt := `CREATE TABLE message_status_table(
    			msgId INTEGER,
    			receiverId TEXT,
    			status TEXT NOT NULL CHECK (status IN ('not_received', 'received', 'read')),
    			PRIMARY KEY (msgId, receiverId),
    			FOREIGN KEY (msgId) REFERENCES chat_messages_table(msgId) ON DELETE CASCADE,
    			FOREIGN KEY (receiverId) REFERENCES users_table(usrId) ON DELETE CASCADE,
    			CONSTRAINT unique_status UNIQUE (msgId, receiverId)
        );`
		_, err = db.Exec(sqlStmt)
		if err != nil {
			return nil, fmt.Errorf("error creating database structure: %w", err)
		}
	}

	// Trigger for auto deleting a chat with no messages
	_, err = db.Exec(`CREATE TRIGGER IF NOT EXISTS delete_empty_chats
						AFTER UPDATE ON chat_messages_table
						BEGIN
							DELETE FROM chats_table
							WHERE chatId = OLD.chatId
							AND NOT EXISTS (SELECT 1 FROM chat_messages_table WHERE chatId = OLD.chatId);
						END;`)
	if err != nil {
		return nil, fmt.Errorf("error initializing db trigger: %w", err)
	}

	// Trigger for auto updating a message delivery status
	_, err = db.Exec(`CREATE TRIGGER IF NOT EXISTS update_message_status
						AFTER UPDATE ON message_status_table
						BEGIN
							UPDATE chat_messages_table
						    SET deliveryStatus = 'read'
						    WHERE msgId = NEW.msgId
						    AND (
						        SELECT COUNT(*)
						        FROM message_status_table
						        WHERE msgId = NEW.msgId AND status != 'read'
						    ) = 0;
							
							UPDATE chat_messages_table
						    SET deliveryStatus = 'received'
						    WHERE msgId = NEW.msgId
						    AND (
						        SELECT COUNT(*)
						        FROM message_status_table
						        WHERE msgId = NEW.msgId AND status != 'received'
						    ) = 0;
						END;`)
	if err != nil {
		return nil, fmt.Errorf("error initializing db trigger: %w", err)
	}

	// Index initialization for faster db interaction used in some function
	_, err = db.Exec(`CREATE INDEX IF NOT EXISTS idx_chat_messages_chatId_timestamp ON chat_messages_table(chatId, timestamp);
							CREATE INDEX IF NOT EXISTS idx_chat_messages_msgId ON chat_messages_table(msgId);
							CREATE INDEX IF NOT EXISTS dx_message_status_receiverId ON message_status_table(receiverId);
							CREATE INDEX IF NOT EXISTS idx_message_status_msgId ON message_status_table(msgId);
							CREATE INDEX IF NOT EXISTS idx_message_status_status_receiverId_chatId ON message_status_table(status, receiverId, msgId);`)
	if err != nil {
		return nil, fmt.Errorf("error initializing db index: %w", err)
	}

	return &appdbimpl{
		c: db,
	}, nil
}

func (db *appdbimpl) Ping() error {
	return db.c.Ping()
}
