### POST request for login
POST http://localhost:3000/session
Content-Type: application/json

{"userName": "fede"}

> {% client.global.set("client_token", response.headers.valueOf("Authorization").split(' ')[1]); client.global.set("usrId", response.body.valueOf()["usrId"]); console.log(client.global.get("usrId")) %}

### POST request for login
POST http://localhost:3000/session
Content-Type: application/json

{"userName": "franco"}

> {% client.global.set("id_amico", response.headers.valueOf("Authorization").split(' ')[1]); client.global.set("usrId", response.body.valueOf()["usrId"]); console.log(client.global.get("usrId")) %}

### POST request for login
POST http://localhost:3000/session
Content-Type: application/json

{"userName": "mara"}

> {% client.global.set("client_token_2", response.headers.valueOf("Authorization").split(' ')[1]); client.global.set("usrId", response.body.valueOf()["usrId"]); console.log(client.global.get("usrId")) %}

### POST request for login
POST http://localhost:3000/session
Content-Type: application/json

{"userName": "ambra"}

> {% client.global.set("client_token_3", response.headers.valueOf("Authorization").split(' ')[1]); client.global.set("usrId", response.body.valueOf()["usrId"]); console.log(client.global.get("usrId")) %}

### POST request for login
POST http://localhost:3000/session
Content-Type: application/json

{"userName": "rosa"}

> {% client.global.set("client_token_4", response.headers.valueOf("Authorization").split(' ')[1]); client.global.set("usrId", response.body.valueOf()["usrId"]); console.log(client.global.get("usrId")) %}

### GET request for listing all the users
GET http://localhost:3000/users
Authorization: Bearer {{client_token}}

> {% response.body["users"].forEach(user =>{
    console.log("userId <"+ user.usrId +">:\n\tuserName -> "+ user.userName +"\n\tuserPhoto -> "+ (user.userPhoto).substring(0,10))
    }); console.log("id amico: ", client.global.get("id_amico")) %}


### GET request for listing the friend info
GET http://localhost:3000/users/{{id_amico}}
Authorization: Bearer {{client_token}}

> {% console.log("nome: "+ response.body["userName"] +"\nfoto: "+ response.body["userPhoto"] +"\nid: "+ response.body["usrId"]) %}

### GET request for retriving fede's chats
GET localhost:3000/chats
Authorization: Bearer {{client_token}}

> {% console.log("chats:"); if(response.body["chats"]){response.body["chats"].forEach(chat => { console.log("\n\tchatId <"+ chat.chatId +">:\n\t\tchatName -> "+ chat.chatName +"\n\t\tchatPhoto -> "+ (chat.chatPhoto).substring(0,10) +"...\n\t\tisGroup -> "+ chat.isGroup +"\n\t\tparticipants-> "+ chat.participants)}); client.global.set("fede_chatId", response.body["chats"][0]["chatId"]);}else{console.log("no chat")} %}


### GET request for retriving friend's chats
GET localhost:3000/chats
Authorization: Bearer {{id_amico}}

> {% console.log("chats:"); if(response.body["chats"]){response.body["chats"].forEach(chat => { console.log("\n\tchatId <"+ chat.chatId +">:\n\t\tchatName -> "+ chat.chatName +"\n\t\tchatPhoto -> "+ (chat.chatPhoto).substring(0,10) +"...\n\t\tisGroup -> "+ chat.isGroup +"\n\t\tparticipants-> "+ chat.participants)}); client.global.set("fede_chatId", response.body["chats"][0]["chatId"]);}else{console.log("no chat")} %}


### GET request for retriving a chat info
GET localhost:3000/chats/{{fede_chatId}}
Authorization: Bearer {{client_token}}

> {% console.log("chatId <"+ response.body["chatId"] +">:\n\tchatName -> "+ response.body["chatName"] +"\n\tchatPhoto -> "+ (response.body["chatPhoto"]).substring(0,10) +"...\n\tisGroup -> "+ response.body["isGroup"] +"\n\tparticipants-> "+ response.body["participants"]) %}


### POST request for starting a new chat
POST localhost:3000/chats
Authorization: Bearer {{client_token}}
Content-Type: application/json

{
  "chatInfo": {
      "chatName": "",
      "chatPhoto": "",
      "isGroup": false,
      "participants": ["{{id_amico}}"]
  },
  "firstMessage": {
      "contentType": "text",
      "content": "ciao zio"
  }
}

> {% client.global.set("fede_chatId", response.body["chatId"]); console.log("Nuova chat info:\n\tchat id: "+ response.body["chatId"] +"\n\tnome chat: "+ response.body["chatName"] +"\n\tchat photo: "+ (response.body["chatPhoto"]).substring(0,10) +"...\n\tpartecipanti: "+ response.body["participants"]) %}


### POST request for sending a message
POST localhost:3000/chats/{{fede_chatId}}/messages
Authorization: Bearer {{client_token}}
Content-Type: application/json

{
  "contentType": "text",
  "content": "ueue mi ricevete?"
}

### POST request for starting a new chat
POST localhost:3000/chats
Authorization: Bearer {{client_token}}
Content-Type: application/json

{
  "chatInfo": {
      "chatName": "",
      "chatPhoto": "",
      "isGroup": false,
      "participants": ["{{client_token_4}}"]
  },
  "firstMessage": {
      "contentType": "text",
      "content": "ciao "
  }
}

> {% client.global.set("fede_chatId", response.body["chatId"]); console.log("Nuova chat info:\n\tchat id: "+ response.body["chatId"] +"\n\tnome chat: "+ response.body["chatName"] +"\n\tchat photo: "+ (response.body["chatPhoto"]).substring(0,10) +"...\n\tpartecipanti: "+ response.body["participants"]) %}

### POST request for starting a new group chat
POST localhost:3000/chats
Authorization: Bearer {{client_token}}
Content-Type: application/json

{
  "chatInfo": {
      "chatName": "Gruppo gay",
      "chatPhoto": "",
      "isGroup": true,
      "participants": ["{{id_amico}}", "{{client_token_2}}", "{{client_token_3}}", "{{client_token_4}}"]
  },
  "firstMessage": {
      "contentType": "text",
      "content": "ciao ragazzi"
  }
}

> {% client.global.set("fede_chatId", response.body["chatId"]); console.log("Nuova chat info:\n\tchat id: "+ response.body["chatId"] +"\n\tnome chat: "+ response.body["chatName"] +"\n\tchat photo: "+ (response.body["chatPhoto"]).substring(0,10) +"...\n\tpartecipanti: "+ response.body["participants"]) %}
