package api

import (
	"Project_WASAtext/service/api/reqcontext"
	"Project_WASAtext/service/database"
	"Project_WASAtext/service/utilitytool"
	"encoding/json"
	"io"
	"net/http"
	"strconv"
	"strings"

	"github.com/julienschmidt/httprouter"
)

func (rt *_router) startNewChat(writer http.ResponseWriter, request *http.Request, _ httprouter.Params, context reqcontext.RequestContext, usrId string) {

	// Limito la memoria per il parsing del form
	err := request.ParseMultipartForm(32 << 20)
	if err != nil {
		context.Logger.WithError(err).Error("Error parsing multipart form")
		http.Error(writer, "Error parsing multipart form", http.StatusBadRequest)
		return
	}

	var chat database.Chat
	chat.ChatId = -1
	// Recupero le info della chat dai dati del form
	chat.ChatName = request.FormValue("chatName")
	chat.IsGroup, err = strconv.ParseBool(request.FormValue("isGroup"))
	if err != nil {
		context.Logger.WithError(err).Error("Error parsing isGroup")
		http.Error(writer, "Bad request - The is group parameter is not valid", http.StatusBadRequest)
		return
	}
	participants := strings.Split(request.FormValue("participants"), ",")
	participants = append(participants, usrId)

	// Controllo se l'utente stia cercando di fare una chat diretta con un altro utente di cui ha già la conversazione
	if !chat.IsGroup {
		var foundId int
		foundId, err = rt.db.FindChatFromParticipants(participants, false)
		context.Logger.WithField("id found", foundId).Info("id of the chat")
		if err != nil {
			context.Logger.WithError(err).WithField("participants", participants).Error("Error checking if there is already a direct chat for this 2 users")
			http.Error(writer, "Internal server error - unable to complete some check for the request", http.StatusInternalServerError)
			return
		}

		// Se la chat è già esistente,restituisco erroer forbidden
		if foundId != -1 {
			context.Logger.WithField("chatId", foundId).Warn("Tried to start a new direct chat when there was already existing one")
			http.Error(writer, "Forbidden - you can't start a new one2one chat whit this user, you already have one", http.StatusForbidden)
			return
		}
	}

	// Carico l'immagine contenuta nella richiesta http
	photoFile, _, err := request.FormFile("chatPhoto")
	if err != nil {
		context.Logger.WithError(err).Error("Error getting file content")
		http.Error(writer, "Internal server error - Error getting file content", http.StatusInternalServerError)
		return
	}
	defer func() {
		err := photoFile.Close()
		if err != nil {
			context.Logger.WithError(err).Error("Error closing file")
		}
	}()

	chat.ChatPhoto, err = io.ReadAll(photoFile)
	if err != nil {
		context.Logger.WithError(err).Error("Error reading file")
		http.Error(writer, "Internal server error - Error reading file", http.StatusInternalServerError)
		return
	}

	if chat.IsGroup {
		if len(chat.ChatPhoto) == 0 {
			chat.ChatPhoto = utilitytool.DefGroupPropicBytes
		}
		if chat.ChatName == "" {
			chat.ChatName = "Gruppo"
		}
	} else {
		chat.ChatPhoto = []byte{}
		chat.ChatName = ""
	}

	// Recupero i dati del messaggio da inviare per iniziare la chat
	textContent := request.FormValue("textContent")

	var photoContent []byte
	// Carico l'immagine contenuta nella richiesta http
	photoContentFile, _, err := request.FormFile("photoContent")
	if err != nil {
		context.Logger.WithError(err).Error("Error getting file content")
		http.Error(writer, "Internal server error - Error getting file content", http.StatusInternalServerError)
		return
	}
	defer func() {
		err := photoContentFile.Close()
		if err != nil {
			context.Logger.WithError(err).Error("Error closing file")
		}
	}()

	// Leggo il contenuto dell'immagine
	photoContent, err = io.ReadAll(photoContentFile)
	if err != nil {
		context.Logger.WithError(err).Error("Error reading file")
		http.Error(writer, "Internal server error - Error reading file", http.StatusInternalServerError)
		return
	}

	if textContent == "" && len(photoContent) == 0 {
		context.Logger.Warn("No text or photo content found in the request for starting a new chat")
		textContent = "first message of the chat - autogenerated"
	}

	chat.ChatId, err = rt.db.InsertNewChat(participants, chat, textContent, photoContent)
	if err != nil {
		context.Logger.WithError(err).Error("unable to insert a new chat in the db")
		http.Error(writer, "Internal server error - unable to create the chat", http.StatusInternalServerError)
		return
	}

	context.Logger.WithField("chatId", chat.ChatId).Debug("chat created successfully")

	chat.Participants, err = rt.db.GetChatParticipantsInfo(chat.ChatId)
	if err != nil {
		context.Logger.WithError(err).Warn("Error getting participant info")
		http.Error(writer, "Internal server error - unable to retrive all the chat info", http.StatusInternalServerError)
		return
	}

	// Controllo se la chat è un gruppo o meno, se non è un gruppo procedo
	// a recuperare le informazioni dell'altro utente partecipante alla chat
	if !chat.IsGroup {
		selectUserInfo := 0
		if chat.Participants[selectUserInfo].UsrId == usrId {
			selectUserInfo = 1
		}

		chat.ChatName = chat.Participants[selectUserInfo].UserName
		chat.ChatPhoto = chat.Participants[selectUserInfo].UserPhoto
	}

	// preparo la risposta, contenente le info della chat
	responseJSON, marshalErr := json.Marshal(chat)
	if marshalErr != nil {
		context.Logger.WithError(marshalErr).Errorf("Failed to marshal the chat")
		http.Error(writer, "Internal server error - failed json conversion", http.StatusInternalServerError)
		return
	}

	writer.Header().Set("Content-Type", "application/json")
	if _, err := writer.Write(responseJSON); err != nil {
		context.Logger.WithError(err).Error("Errore preaparazione risposta html")
		http.Error(writer, "Internal server error", http.StatusInternalServerError)
		return
	}
}
